"""
Pydantic models for the ACCT backend.

Defines schemas for:
- Risk Events
- Action Cards
- Workflow State
- Forecasts
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class RiskEvent(BaseModel):
    """A detected risk event."""
    event_id: str
    event_type: str
    severity: str  # critical, high, medium, low
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    metric_name: Optional[str] = None
    current_value: Optional[float] = None
    threshold_value: Optional[float] = None
    unit: Optional[str] = None
    affected_units: List[str] = Field(default_factory=list)
    related_patient_ids: List[str] = Field(default_factory=list)


class CitedSource(BaseModel):
    """A cited source from RAG."""
    source_id: str
    source_title: str
    relevance_score: float = 0.0


class ProposedAction(BaseModel):
    """A proposed action within an ActionCard."""
    action_type: str  # transfer, discharge, escalate, alert, consult
    target_patients: List[str] = Field(default_factory=list)
    description: str
    rationale: str
    steps: List[str] = Field(default_factory=list)


class ActionCard(BaseModel):
    """An action card generated by the Planning Agent."""
    card_id: str
    title: str
    summary: str
    urgency: str  # critical, high, medium, low
    status: str = "pending"  # pending, approved, rejected, completed
    proposed_actions: List[ProposedAction] = Field(default_factory=list)
    cited_sources: List[CitedSource] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    approved_by: Optional[str] = None
    approved_at: Optional[datetime] = None


class AgentState(str, Enum):
    """Current state in the agentic workflow."""
    IDLE = "idle"
    MONITORING = "monitoring"
    RETRIEVING = "retrieving"
    PLANNING = "planning"
    VALIDATING = "validating"
    NOTIFYING = "notifying"
    COMPLETED = "completed"
    FAILED = "failed"


class ActionType(str, Enum):
    """Types of actions the system can recommend."""
    DISCHARGE = "discharge"
    TRANSFER = "transfer"
    ESCALATE = "escalate"
    MEDICATION_ADJUSTMENT = "medication_adjustment"
    PROCEDURE = "procedure"
    CONSULT = "consult"
    MONITOR = "monitor"


class WorkflowState(BaseModel):
    """State of an agent workflow."""
    workflow_id: str
    status: str = "pending"
    current_agent: Optional[str] = None
    iteration: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ForecastPoint(BaseModel):
    """A single point in a forecast."""
    timestamp: datetime
    predicted_value: float
    lower_bound: float
    upper_bound: float
    actual_value: Optional[float] = None


class CapacityForecast(BaseModel):
    """A capacity forecast for a metric."""
    metric_name: str
    unit: str
    forecast_horizon_hours: int
    data_points: List[ForecastPoint] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
